server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    '[com.ctp.consent]': ${LOG_LEVEL_APP:INFO}
    '[org.springframework.security]': ${LOG_LEVEL_SECURITY:INFO}
    '[org.hibernate.SQL]': ${LOG_LEVEL_SQL:INFO}
  pattern:
    # console: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%highlight(%5level)] %cyan(%logger{0}) : %msg%n'
    console: "[%highlight(%5level)] %cyan(%logger{0}) : %msg%n"
  file:
    name: ${LOG_FILE:logs/consent.log}
    max-size: ${LOG_FILE_MAX_SIZE:10MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}

app:
  file:
    upload-dir: ./uploads
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKeyForJWTShouldBeVeryLongAndSecureAtLeast512BitsForHS512Algorithm}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours
    password:
      strength: 10
    remember-me:
      key: ${REMEMBER_ME_KEY:mySecretRememberMeKeyForSpringSecurityRememberMeAuthentication}
      validity: ${REMEMBER_ME_VALIDITY:1209600} # 14 days in seconds
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    max-age: 3600

spring:
  application:
    name: consent
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/ctp?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your_password_here}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    show-sql: false
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${app.file.upload-dir}/
      cache:
        period: 3600
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
    problemdetails:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      file-size-threshold: 2KB
