server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
    path: /error
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    '[com.ctp.consent]': ${LOG_LEVEL_APP:INFO}
    '[org.springframework.security]': ${LOG_LEVEL_SECURITY:INFO}
    '[org.hibernate.SQL]': ${LOG_LEVEL_SQL:INFO}
    '[org.springframework.web.servlet]': ${LOG_LEVEL_RESOURCE:ERROR}
  pattern:
    # console: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%highlight(%5level)] %cyan(%logger{0}) : %msg%n'
    console: "[%highlight(%5level)] %cyan(%logger{0}) : %msg%n"
  file:
    name: ${LOG_FILE:logs/consent.log}
    max-size: ${LOG_FILE_MAX_SIZE:10MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}

app:
  security:
    remember-me:
      key: ${REMEMBER_ME_KEY:mySecretRememberMeKeyForSpringSecurityRememberMeAuthentication}
      validity: ${REMEMBER_ME_VALIDITY:1209600} # 14 days in seconds

spring:
  application:
    name: consent
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ctp?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your_password_here}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  web:
    resources:
      static-locations:
        - classpath:/static/
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
    problemdetails:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      file-size-threshold: 2KB
